#
# Toolbar config file
#
---
:model: ConfiguredSystemForeman
:button_groups:
- :name: provider_foreman_lifecycle
  :items:
  - :buttonSelect: provider_foreman_lifecycle_choice
    :image: lifecycle
    :title: Lifecycle
    :text: Lifecycle
    :enabled: 'true'
    :items:
    - :button: provider_foreman_provision
      :image: new
      :text: "Provision Configured Systems"
      :title: "Provision Configured Systems"
      :url: provision
      :url_parms: 'main_div'
      :enabled: 'false'
      :onwhen: '1+'
