#
# Toolbar config file
#
---
:model: ConfigurationProfile
:button_groups:
- :name: provider_vmdb
  :items:
  - :buttonSelect: provider_vmdb_choice
    :image: vmdb
    :title: Configuration
    :text: Configuration
    :enabled: 'true'
    :items:
    - :button: provider_foreman_refresh
      :image: refresh
      :text: "Refresh Relationships and Power states"
      :title: "Refresh relationships for all items related to this Foreman Provider"
      :url: refresh
      :confirm: "Refresh relationships for all items related to this Foreman Provider?"
    - :separator:
    - :button: provider_foreman_edit
      :image: edit
      :text: Edit this Foreman Provider
      :title: Edit this Foreman Provider
      :url: edit
    - :button: provider_foreman_delete
      :image: remove
      :text: Remove this Foreman Provider from the VMDB
      :title: Remove this Foreman Provider from the VMDB
      :url: delete
      :confirm: "Warning: The selected Foreman Provider and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Foreman Provider?"
