#
# Toolbar config file
#
---
:model: ConfiguredSystemForeman
:button_groups:
- :name: record_summary
  :items:
  - :buttonSelect: provider_foreman_lifecycle_choice
    :image: lifecycle
    :title: Lifecycle
    :text: Lifecycle
    :enabled: 'true'
    :items:
    - :button: provider_foreman_provision
      :image: new
      :text: "Provision Configured System"
      :title: "Provision Configured System"
      :url: provision
      :url_parms: 'main_div'
      :enabled: 'true'
