languages:
  Ruby: true
  JavaScript: true
exclude_paths:
- "app/assets/javascripts/dhtmlx*/*"
- "gems/pending/spec/*"
- "gems/pending/test/*"
- "gems/pending/*/test/*"
- "public/javascripts/timeline/*"
- "spec/*"
- "test/*"
