#
# Overrides
#
Rails:
  Enabled: true

Metrics/AbcSize:
  Max: 20
  Severity: refactor
Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Metrics/BlockNesting:
  Severity: refactor
Metrics/ClassLength:
  Severity: refactor
Style/ClassCheck:
  EnforcedStyle: kind_of?
Style/CollectionMethods:
  PreferredMethods:
    find: detect
    find_all: select
    map: collect
    reduce: inject
Metrics/CyclomaticComplexity:
  Severity: refactor
Style/FormatString:
  EnforcedStyle: percent
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Metrics/LineLength:
  Max: 120
  Severity: refactor
Metrics/MethodLength:
  Max: 25
  Severity: refactor
Metrics/ParameterLists:
  Severity: refactor
Metrics/PerceivedComplexity:
  Severity: refactor
Style/RedundantReturn:
  AllowMultipleReturnValues: true
Style/SignalException:
  EnforcedStyle: only_raise
Style/SingleLineMethods:
  AllowIfMethodIsEmpty: false
Style/TrivialAccessors:
  AllowPredicates: true
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
#
# Enabled/Disabled
#
Style/ClassAndModuleChildren:
  Enabled: false
Lint/DefEndAlignment:
  AutoCorrect: true
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Lint/EndAlignment:
  AutoCorrect: true
Style/ExtraSpacing:
  AutoCorrect: true
Rails/FindEach:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NumericLiterals:
  AutoCorrect: false
Style/ParallelAssignment:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Rails/ReadWriteAttribute:
  AutoCorrect: false
Style/RescueModifier:
  AutoCorrect: false
Style/SingleLineBlockParams:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/SpecialGlobalVars:
  AutoCorrect: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  AutoCorrect: false
