language: ruby
rvm: 1.9.3
env:
  global:
  - BUNDLE_WITHOUT=development:metric_fu:qpid
  - RUBY_GC_MALLOC_LIMIT=90000000
  matrix:
  - TEST_SUITE=lib         TEST_ROOT=lib
  - TEST_SUITE=vmdb        TEST_ROOT=vmdb
  - TEST_SUITE=migrations  TEST_ROOT=vmdb
  - TEST_SUITE=replication TEST_ROOT=vmdb
  - TEST_SUITE=automation  TEST_ROOT=vmdb
  - TEST_SUITE=javascript  TEST_ROOT=vmdb
addons:
  postgresql: '9.3'
before_install:
- "echo 'gem: --no-ri --no-rdoc --no-document' > ~/.gemrc"
- psql -c "CREATE USER root SUPERUSER PASSWORD 'smartvm';" -U postgres
- rake build:shared_objects
- cd $TEST_ROOT
before_script: bundle exec rake test:$TEST_SUITE:setup
script: bundle exec rake test:$TEST_SUITE
