---
http_interactions:
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Tue, 22 Nov 2016 16:27:57 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=fae6b852e584aed1966a9104cdee8d12; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}'
    http_version: 
  recorded_at: Tue, 22 Nov 2016 16:27:57 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/counters/machine%2Fcapture.context.com%2Fcpu%2Fusage/stats/?bucketDuration=20s&start=1468235823000
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/json
      Date:
      - Tue, 22 Nov 2016 16:27:58 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=fae6b852e584aed1966a9104cdee8d12; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '[{"start":1468235823000,"end":1468235843000,"empty":true},{"start":1479832063000,"end":1479832083000,"min":4.837839594638E12,"avg":4.837839594638E12,"median":4.837839594638E12,"max":4.837839594638E12,"sum":4.837839594638E12,"samples":1,"empty":false}]'
    http_version: 
  recorded_at: Tue, 22 Nov 2016 16:28:00 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Tue, 22 Nov 2016 16:28:03 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=fae6b852e584aed1966a9104cdee8d12; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}'
    http_version: 
  recorded_at: Tue, 22 Nov 2016 16:28:03 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/gauges/machine%2Fcapture.context.com%2Fmemory%2Fusage/stats/?bucketDuration=20s&start=1468235843000
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/json
      Date:
      - Tue, 22 Nov 2016 16:28:03 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=fae6b852e584aed1966a9104cdee8d12; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '[{"start":1468235843000,"end":1468235863000,"empty":true},{"start":1479832083000,"end":1479832103000,"empty":true}]'
    http_version: 
  recorded_at: Tue, 22 Nov 2016 16:28:05 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Tue, 22 Nov 2016 16:28:08 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=fae6b852e584aed1966a9104cdee8d12; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}'
    http_version: 
  recorded_at: Tue, 22 Nov 2016 16:28:08 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/counters/machine%2Fcapture.context.com%2Fnetwork%2Ftx/stats/?bucketDuration=20s&start=1468235823000
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/json
      Date:
      - Tue, 22 Nov 2016 16:28:08 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=fae6b852e584aed1966a9104cdee8d12; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '[{"start":1468235823000,"end":1468235843000,"empty":true},{"start":1479832083000,"end":1479832103000,"empty":true}]'
    http_version: 
  recorded_at: Tue, 22 Nov 2016 16:28:10 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Tue, 22 Nov 2016 16:28:12 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=fae6b852e584aed1966a9104cdee8d12; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}'
    http_version: 
  recorded_at: Tue, 22 Nov 2016 16:28:12 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/counters/machine%2Fcapture.context.com%2Fnetwork%2Frx/stats/?bucketDuration=20s&start=1468235823000
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/json
      Date:
      - Tue, 22 Nov 2016 16:28:13 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=fae6b852e584aed1966a9104cdee8d12; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '[{"start":1468235823000,"end":1468235843000,"empty":true},{"start":1479832083000,"end":1479832103000,"empty":true}]'
    http_version: 
  recorded_at: Tue, 22 Nov 2016 16:28:15 GMT
recorded_with: VCR 3.0.3
