---
http_interactions:
- request:
    method: get
    uri: https://yzamir-centos7-1.example.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer TheToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '136'
      Date:
      - Wed, 27 Jul 2016 16:35:53 GMT
      Set-Cookie:
      - OPENSHIFT_REENCRYPT_openshift-infra_hawkular-metrics_SERVERID=33cc0c3faeb21e60f21e6c0b4677d13c;
        path=/; HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.18.0-SNAPSHOT","Built-From-Git-SHA1":"65404bcc24e76f005a438ce0022fc2cfd7c90267"}'
    http_version: 
  recorded_at: Wed, 27 Jul 2016 16:35:53 GMT
- request:
    method: get
    uri: https://yzamir-centos7-1.example.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer TheToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '136'
      Date:
      - Wed, 27 Jul 2016 16:35:54 GMT
      Set-Cookie:
      - OPENSHIFT_REENCRYPT_openshift-infra_hawkular-metrics_SERVERID=33cc0c3faeb21e60f21e6c0b4677d13c;
        path=/; HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.18.0-SNAPSHOT","Built-From-Git-SHA1":"65404bcc24e76f005a438ce0022fc2cfd7c90267"}'
    http_version: 
  recorded_at: Wed, 27 Jul 2016 16:35:54 GMT
recorded_with: VCR 3.0.3
