---
base: &base
  host: localhost
  port: 9092
  protocol: Kafka
  encoding: json
  sasl.mechanism: PLAIN
  sasl.username: admin
  sasl.password: smartvm

development:
  <<: *base

production:
  <<: *base

test:
  <<: *base
