---
:base_tables:
  - AuditEvent
  - AvailabilityZone
  - BottleneckEvent
  - ChargebackVm
  - ChargebackContainerProject
  - ChargebackContainerImage
  - CloudResourceQuota
  - CloudTenant
  - CloudVolume
  - Compliance
  - ManageIQ::Providers::Foreman::ConfigurationManager::ConfiguredSystem
  - ManageIQ::Providers::ConfigurationManager
  - Container
  - ContainerBuild
  - ContainerPerformance
  - ContainerGroup
  - ContainerGroupPerformance
  - ContainerImage
  - ContainerImageRegistry
  - ContainerNode
  - ContainerNodePerformance
  - ContainerProject
  - ContainerProjectPerformance
  - ContainerReplicator
  - ContainerRoute
  - ContainerService
  - ContainerTemplate
  - PersistentVolume
  - ManageIQ::Providers::CloudManager
  - EmsCluster
  - EmsClusterPerformance
  - EmsEvent
  - ManageIQ::Providers::InfraManager
  - ExtManagementSystem
  - ExtManagementSystemPerformance
  - Flavor
  - GuestApplication
  - Host
  - HostAggregate
  - HostPerformance
  - MiqGroup
  - MiqRegion
  - MiqRequest
  - MiqServer
  - MiqTemplate
  - MiqWorker
  - OntapFileShare
  - OntapLogicalDisk
  - OntapStorageSystem
  - OntapStorageVolume
  - OntapVolumeMetricsRollup
  - OrchestrationStack
  - OrchestrationTemplate
  - PolicyEvent
  - ResourcePool
  - SecurityGroup
  - Service
  - ServiceTemplate
  - Storage
  - StorageFile
  - StoragePerformance
  - Switch
  - ManageIQ::Providers::CloudManager::Template
  - ManageIQ::Providers::InfraManager::Template
  - Tenant
  - User
  - VimPerformanceTrend
  - Vm
  - ManageIQ::Providers::CloudManager::Vm
  - ManageIQ::Providers::InfraManager::Vm
  - VmPerformance
  - Zone
