---
:base_tables:
  - AuditEvent
  - AvailabilityZone
  - BottleneckEvent
  - ChargebackVm
  - ChargebackContainerProject
  - ChargebackContainerImage
  - CloudResourceQuota
  - CloudTenant
  - CloudVolume
  - Compliance
  - ManageIQ::Providers::Foreman::ConfigurationManager::ConfiguredSystem
  - ManageIQ::Providers::ConfigurationManager
  - Container
  - ContainerBuild
  - ContainerPerformance
  - ContainerGroup
  - ContainerGroupPerformance
  - ContainerImage
  - ContainerImageRegistry
  - ContainerNode
  - ContainerNodePerformance
  - ContainerProject
  - ContainerProjectPerformance
  - ContainerReplicator
  - ContainerRoute
  - ContainerService
  - ContainerTemplate
  - PersistentVolume
  - ManageIQ::Providers::CloudManager
  - EmsCluster
  - EmsClusterPerformance
  - EmsEvent
  - ManageIQ::Providers::InfraManager
  - ExtManagementSystem
  - ExtManagementSystemPerformance
  - Flavor
  - GuestApplication
  - Host
  - HostAggregate
  - HostPerformance
  - MiqGroup
  - MiqRegion
  - MiqRequest
  - MiqServer
  - MiqTemplate
  - MiqWorker
  - OntapFileShare
  - OntapLogicalDisk
  - OntapStorageSystem
  - OntapStorageVolume
  - OntapVolumeMetricsRollup
  - OrchestrationStack
  - OrchestrationTemplate
  - PolicyEvent
  - ResourcePool
  - SecurityGroup
  - Service
  - ServiceTemplate
  - Storage
  - StorageFile
  - StoragePerformance
  - Switch
  - ManageIQ::Providers::CloudManager::Template
  - ManageIQ::Providers::InfraManager::Template
  - Tenant
  - User
  - VimPerformanceTrend
  - Vm
  - ManageIQ::Providers::CloudManager::Vm
  - ManageIQ::Providers::InfraManager::Vm
  - VmPerformance
  - Zone
:include_tables:
  - advanced_settings
  - archived_container_groups
  - audit_events
  - availability_zones
  - cloud_networks
  - cloud_resource_quotas
  - cloud_tenants
  - compliances
  - compliance_details
  - computer_systems
  - configuration_profiles
  - configuration_managers
  - configured_systems
  - containers
  - container_groups
  - container_projects
  - container_images
  - container_nodes
  - customization_scripts
  - customization_script_media
  - customization_script_ptables
  - disks
  - ems_events
  - ems_clusters
  - ems_custom_attributes
  - evm_owners
  - event_logs
  - ext_management_systems
  - filesystem_drivers
  - filesystems
  - firewall_rules
  - flavors
  - groups
  - guest_applications
  - guest_devices
  - hardwares
  - hosts
  - host_aggregates
  - host_services
  - kernel_drivers
  - key_pairs
  - lans
  - last_compliances
  - linux_initprocesses
  - miq_actions
  - miq_approval_stamps
  - miq_custom_attributes
  - miq_policy_sets
  - miq_provisions
  - miq_regions
  - miq_requests
  - miq_scsi_luns
  - miq_servers
  - miq_workers
  - ontap_concrete_extents
  - ontap_file_shares
  - ontap_logical_disks
  - ontap_plex_extents
  - ontap_raid_group_extents
  - ontap_storage_systems
  - ontap_storage_volumes
  - openscap_results
  - openscap_rule_results
  - orchestration_stack_outputs
  - orchestration_stack_parameters
  - orchestration_stack_resources
  - orchestration_templates
  - operating_system_flavors
  - partitions
  - ports
  - processes
  - miq_provision_templates
  - miq_provision_vms
  - miq_templates
  - networks
  - nics
  - operating_systems
  - patches
  - registry_items
  - resource_pools
  - security_groups
  - service_templates
  - services
  - snapshots
  - stacks
  - storages
  - storage_adapters
  - storage_files
  - switches
  - tenant_quotas
  - users
  - vms
  - volumes
  - win32_services
  - zones
  - storage_systems
  - file_systems
  - hosted_file_shares
  - file_shares
  - logical_disks
  - storage_volumes
  - base_storage_extents
  - top_storage_extents
