---
- :vi
- :svc
- :clo
- :inf
- :con
- :aut
- :opt
- :set
- ems-type:foreman_configuration
- ems-type:scvmm
- ems-type:openstack_infra
- ems-type:rhevm
- ems-type:vmwarews
- ems-type:ec2
- ems-type:openstack
- ems-type:kubernetes
- ems-type:foreman_provisioning
