--- 
where_clause: 
dims: 
created_on: 2009-01-12 14:37:34.291952 Z
title: VDI VM OS Configuration
conditions: !ruby/object:MiqExpression 
  exp: 
    CONTAINS: 
      tag: Vm.managed-function
      value: desktop
updated_on: 2009-01-12 14:38:04.078862 Z
order: Ascending
graph: 
menu_name: VDI VM OS Configuration
rpt_group: Custom
priority: 25
col_order: 
- name
- host.name
- hardware.size_on_disk
- operating_system.product_key
- operating_system.product_name
- operating_system.service_pack
- operating_system.version
- users.name
- networks.hostname
timeline: 
id: 164
file_mtime: 
categories: 
rpt_type: Custom
filename: 
include: 
  hardware: 
    columns: 
    - size_on_disk
    include: 
      networks: 
        columns: 
        - hostname
  operating_system: 
    columns: 
    - product_key
    - product_name
    - service_pack
    - version
  host: 
    columns: 
    - name
  users: 
    columns: 
    - name
db: Vm
cols: 
- name
template_type: report
group: y
sortby: 
- name
headers: 
- VM Name
- Host Name
- Size
- OS Product Key
- OS Product Name
- OS Service Pack
- OS Version
- User Name
- Network Hostname
