# PostgreSQL
#
# Development version of database.yml handles switching between version branches where migrations apply.  Examples:
#   master  => vmdb_development
#   5.2.x   => vmdb_development_5_2
#   5.2.1.x => vmdb_development_5_2
#
# <% unless $db_yml_loaded %>
# <%   $db_yml_loaded = true %>
# <%   evm_version = File.read(File.join(Rails.root, 'VERSION')).chomp rescue '9.9.9.9' %>
# <%   db_suffix = (evm_version == '9.9.9.9') ? '' : "_#{evm_version.split('.')[0..1].join('_')}" %>
# <%   c = YAML.load_file(Rails.root.join("config", "database.yml"))[Rails.env] %>
# <%   c.keys.each { |k| c[k] = ERB.new(v = c[k], nil, nil, 'v').result(binding).lines.first if c[k].is_a?(String) } %>
# <%   puts "** EVM v#{evm_version}; Database: adapter=#{c["adapter"]}, name=#{c["database"]}, host=#{c["host"]}" %>
# <% end %>
---
base: &base
  adapter: postgresql
  encoding: utf8
  username: root
  pool: 1
  wait_timeout: 5

development:
  <<: *base
  database: vmdb_development<%=db_suffix %>

production:
  <<: *base
  database: vmdb_production<%=db_suffix %>

test: &test
  <<: *base
  pool: 3
  database: vmdb_test<%=db_suffix %>
  # Silence these: 'NOTICE:  CREATE TABLE will create...'
  min_messages: warning

metric_fu:
  <<: *test
